DROP table flavors CASCADE;
DROP table mtm_flavor2product CASCADE;
DROP table mtm_orders2customers CASCADE;
DROP table login_record CASCADE;
DROP table customer_data CASCADE;
DROP table account_info CASCADE;
DROP table customers CASCADE;
DROP table orders CASCADE;
DROP table products CASCADE;